/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import controles.GenerosJpaController;
import controles.MediosJpaController;
import entidades.Generos;
import entidades.Medios;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco
 */
public class VentanaMedio extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    public static EntityManagerFactory emf = Persistence.createEntityManagerFactory("proyectoJPAPU");
    MediosJpaController jpaMedios = new MediosJpaController(emf);
    GenerosJpaController jpaGeneros = new GenerosJpaController(emf);
    List listaMedios = jpaMedios.findMediosEntities();
    Medios medio = new Medios();
    Generos genero = new Generos();

    /**
     * Creates new form FramePrincipal
     */
    public VentanaMedio() {
        initComponents();
        this.setLocationRelativeTo(null);
        dtm = (DefaultTableModel) tablaMedios.getModel();
        tablaMedios.setModel(dtm);
        mostrarGeneros();
        botonActualizar.setEnabled(false);
        botonEliminar.setEnabled(false);

    }

    private void mostrarMedios() {
        setModel(tablaMedios);
        DefaultTableModel modelo = (DefaultTableModel) tablaMedios.getModel();
        try {
            jpaMedios.insertarModelo(modelo);
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void mostrarGeneros() {
        setModel(tablaGeneros);
        DefaultTableModel modelo = (DefaultTableModel) tablaGeneros.getModel();
        try {
            jpaGeneros.insertarModelo(modelo);
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void setModel(JTable table) {
        while (table.getRowCount() > 0) {
            ((DefaultTableModel) table.getModel()).removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaGeneros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoClave = new javax.swing.JTextField();
        campoTitulo = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMedios = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoTipoMedio = new javax.swing.JTextField();
        campoDuracion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonMostrarTodos = new javax.swing.JButton();
        campoClaveGenero = new javax.swing.JTextField();
        botonRegresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Medio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaGeneros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre", "Tipo de Medio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaGeneros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaGenerosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablaGeneros);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 344, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Clave:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 43, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Titulo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 83, -1, -1));
        getContentPane().add(campoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 111, -1));
        getContentPane().add(campoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 236, -1));

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 250, -1, -1));

        tablaMedios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Titulo", "Tipo de Medio", "Duración", "Clave del Genero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMedios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMediosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMedios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 610, 110));

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 250, -1, -1));

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(botonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tipo Medio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 119, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Duración:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 161, -1, -1));
        getContentPane().add(campoTipoMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 95, -1));
        getContentPane().add(campoDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 95, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("minutos.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Clave del Genero:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 201, -1, -1));

        botonMostrarTodos.setText("Mostrar Todos");
        botonMostrarTodos.setFocusable(false);
        botonMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarTodosActionPerformed(evt);
            }
        });
        getContentPane().add(botonMostrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 115, -1, 50));
        getContentPane().add(campoClaveGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 95, -1));

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, -1, 29));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Diapositiva2.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        String claveGenero = campoClaveGenero.getText();
        String Clave = campoClave.getText();
        String Titulo = campoTitulo.getText();
        String TipoMedio = campoTipoMedio.getText();
        int Duracion = Integer.parseInt(campoDuracion.getText());
        genero.setCveGenero(claveGenero);

        medio.setClave(Clave);
        medio.setTitutlo(Titulo);
        medio.setTipoMedio(TipoMedio);
        medio.setDuracion(Duracion);
        medio.setCveGenero(genero);
        try {
            jpaMedios.create(medio);
            setModel(tablaGeneros);
            mostrarGeneros();
            campoClave.setText(null);
            campoTitulo.setText(null);
            campoTipoMedio.setText(null);
            campoDuracion.setText(null);
            campoClaveGenero.setText(null);
            JOptionPane.showMessageDialog(null, "Medio agregado correctamente");
        } catch (Exception e) {
            Logger.getLogger(VentanaMedio.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        String claveGenero = campoClaveGenero.getText();
        genero.setCveGenero(claveGenero);
        medio.setClave(campoClave.getText());
        medio.setTitutlo(campoTitulo.getText());
        medio.setTipoMedio(campoTipoMedio.getText());
        medio.setDuracion(Integer.parseInt(campoDuracion.getText()));
        medio.setCveGenero(genero);
        
        try {
            jpaMedios.edit(medio);
            campoClave.setText(null);
            campoTitulo.setText(null);
            campoTipoMedio.setText(null);
            campoDuracion.setText(null);
            campoClaveGenero.setText(null);
            setModel(tablaGeneros);
            mostrarGeneros();
            JOptionPane.showMessageDialog(null, "Medio actualizado correctamente");
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarTodosActionPerformed
        mostrarMedios();
    }//GEN-LAST:event_botonMostrarTodosActionPerformed

    private void tablaGenerosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaGenerosMousePressed
        int fila = tablaGeneros.getSelectedRow();
        if (fila >= 0) {
            campoClaveGenero.setText(tablaGeneros.getValueAt(fila, 0).toString());
        } else {
            JOptionPane.showMessageDialog(null, "NO A SELECCIONADO NINGUN GENERO");
        }
    }//GEN-LAST:event_tablaGenerosMousePressed

    private void tablaMediosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMediosMousePressed
        int fila = tablaMedios.getSelectedRow();
        if (fila >= 0) {
            campoClave.setText(tablaMedios.getValueAt(fila, 0).toString());
            campoTitulo.setText(tablaMedios.getValueAt(fila, 1).toString());
            campoTipoMedio.setText(tablaMedios.getValueAt(fila, 2).toString());
            campoDuracion.setText(tablaMedios.getValueAt(fila, 3).toString());
            botonEliminar.setEnabled(true);
            botonActualizar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "NO A SELECCIONADO NINGUN MEDIO");
        }
    }//GEN-LAST:event_tablaMediosMousePressed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        String clave = campoClave.getText();

        medio.setClave(clave);

        try {
            jpaMedios.destroy(campoClave.getText());
            setModel(tablaMedios);
            mostrarMedios();
            campoClave.setText(null);
            campoTitulo.setText(null);
            campoTipoMedio.setText(null);
            campoDuracion.setText(null);
            campoClaveGenero.setText(null);
            JOptionPane.showMessageDialog(null, "Medio eliminado correctamente");
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.dispose();
        MenuPrincipal menu;
        menu = new MenuPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_botonRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonMostrarTodos;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JTextField campoClave;
    private javax.swing.JTextField campoClaveGenero;
    private javax.swing.JTextField campoDuracion;
    private javax.swing.JTextField campoTipoMedio;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaGeneros;
    private javax.swing.JTable tablaMedios;
    // End of variables declaration//GEN-END:variables

}
