/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import controles.PeliculasJpaController;
import entidades.Peliculas;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import objetosServicio.Fecha;

/**
 *
 * @author Francisco
 */
public class VentanaPelicula extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    public static EntityManagerFactory emf = Persistence.createEntityManagerFactory("proyectoJPAPU");
    PeliculasJpaController jpaPeliculas = new PeliculasJpaController(emf);
    List listaPeliculas = jpaPeliculas.findPeliculasEntities();
    Peliculas peliculas = new Peliculas();

    /**
     * Creates new form FramePrincipal
     */
    public VentanaPelicula() {
        initComponents();
        this.setLocationRelativeTo(null);
        dtm = (DefaultTableModel) tablaPeliculas.getModel();
        tablaPeliculas.setModel(dtm);
        campoFecha.setText(new Fecha().toString());
        botonActualizar.setEnabled(false);
        botonEliminar.setEnabled(false);
    }

    private void mostrarPeliculas() {
        setModel(tablaPeliculas);
        DefaultTableModel modelo = (DefaultTableModel) tablaPeliculas.getModel();
        try {
            jpaPeliculas.insertarModelo(modelo);
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void setModel(JTable table) {
        while (table.getRowCount() > 0) {
            ((DefaultTableModel) table.getModel()).removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoClave = new javax.swing.JTextField();
        campoDirector = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPeliculas = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoFecha = new javax.swing.JFormattedTextField();
        botonMostrarTodos = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Pelicula");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Clave:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 43, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Director:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 81, -1, -1));
        getContentPane().add(campoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 111, -1));
        getContentPane().add(campoDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 236, -1));

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        tablaPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre Actor", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaPeliculasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPeliculas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 560, 190));

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(botonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fecha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 118, -1, -1));

        campoFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(campoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 115, -1));

        botonMostrarTodos.setText("Mostrar Todos");
        botonMostrarTodos.setFocusable(false);
        botonMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarTodosActionPerformed(evt);
            }
        });
        getContentPane().add(botonMostrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, 50));

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 501, -1, 39));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Diapositiva2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        String Clave = campoClave.getText();
        String Director = campoDirector.getText();

        peliculas.setClave(Clave);
        peliculas.setDirector(Director);
        peliculas.setFecha(new Date(campoFecha.getText()));
        try {
            jpaPeliculas.create(peliculas);
            campoClave.setText(null);
            campoFecha.setText(null);
            campoDirector.setText(null);
            setModel(tablaPeliculas);
            mostrarPeliculas();
            JOptionPane.showMessageDialog(null, "Pelicula agregada correctamente");
        } catch (Exception e) {
            Logger.getLogger(VentanaPelicula.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        peliculas.setClave(campoClave.getText());
        peliculas.setDirector(campoDirector.getText());
        peliculas.setFecha(new Date(campoFecha.getText()));

        try {
            jpaPeliculas.edit(peliculas);
            campoClave.setText(null);
            campoFecha.setText(null);
            campoDirector.setText(null);
            setModel(tablaPeliculas);
            mostrarPeliculas();
            JOptionPane.showMessageDialog(null, "Pelicula actualizada correctamente");
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarTodosActionPerformed
        mostrarPeliculas();
    }//GEN-LAST:event_botonMostrarTodosActionPerformed

    private void tablaPeliculasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPeliculasMousePressed
        int fila = tablaPeliculas.getSelectedRow();
        if (fila >= 0) {
            campoClave.setText(tablaPeliculas.getValueAt(fila, 0).toString());
            campoDirector.setText(tablaPeliculas.getValueAt(fila, 1).toString());
            campoFecha.setText(tablaPeliculas.getValueAt(fila, 2).toString());
            botonEliminar.setEnabled(true);
            botonActualizar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "NO A SELECCIONADO NINGUNA PELICULA");
        }
    }//GEN-LAST:event_tablaPeliculasMousePressed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        peliculas.setClave(campoClave.getText());

        try {
            jpaPeliculas.destroy(campoClave.getText());
            setModel(tablaPeliculas);
            mostrarPeliculas();
            campoClave.setText(null);
            campoFecha.setText(null);
            campoDirector.setText(null);
            JOptionPane.showMessageDialog(null, "Pelicula eliminada correctamente");
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.dispose();
        MenuPrincipal menu;
        menu = new MenuPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_botonRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonMostrarTodos;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JTextField campoClave;
    private javax.swing.JTextField campoDirector;
    private javax.swing.JFormattedTextField campoFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPeliculas;
    // End of variables declaration//GEN-END:variables
}
