/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import controles.ActoresJpaController;
import entidades.Actores;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco
 */
public class VentanaActor extends javax.swing.JFrame {

    DefaultTableModel dtm;
    public static EntityManagerFactory emf = Persistence.createEntityManagerFactory("proyectoJPAPU");
    ActoresJpaController jpaActores = new ActoresJpaController(emf);
    List listaActores = jpaActores.findActoresEntities();
    Actores actor = new Actores("1", "x");

    /**
     * Creates new form FramePrincipal
     */
    public VentanaActor() {
        initComponents();
        this.setLocationRelativeTo(null);
        dtm = (DefaultTableModel) tablaActores.getModel();
        tablaActores.setModel(dtm);
        botonActualizar.setEnabled(false);
        botonEliminar.setEnabled(false);
    }

    private void mostrarActores() {
        setModel(tablaActores);
        DefaultTableModel modelo = (DefaultTableModel) tablaActores.getModel();
        try {
            jpaActores.insertarModelo(modelo);
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void setModel(JTable table) {
        while (table.getRowCount() > 0) {
            ((DefaultTableModel) table.getModel()).removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoClave = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaActores = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana Actor");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Clave:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Actor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        getContentPane().add(campoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 111, -1));
        getContentPane().add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 236, -1));

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 132, -1, -1));

        tablaActores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre Actor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaActores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaActoresMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaActores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 500, 190));

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 132, -1, -1));

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(botonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 132, -1, -1));

        botonMostrar.setText("Mostrar Todos");
        botonMostrar.setFocusable(false);
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, 50));

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 483, -1, 33));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Diapositiva2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        String Clave = campoClave.getText();
        String Nombre = campoNombre.getText();

        Actores actor = new Actores();
        actor.setCveActor(Clave);
        actor.setNombre(Nombre);

        try {
            jpaActores.create(actor);
            campoClave.setText(null);
            campoNombre.setText(null);
            setModel(tablaActores);
            mostrarActores();
            JOptionPane.showMessageDialog(null, "Actor agregado correctamente");
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
      
        actor.setCveActor(campoClave.getText());
        actor.setNombre(campoNombre.getText());
        try {
            jpaActores.edit(actor);
           
            campoClave.setText(null);
            campoNombre.setText(null);
            setModel(tablaActores);
            mostrarActores();
            JOptionPane.showMessageDialog(null, "Actor actualizado correctamente");
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        mostrarActores();

    }//GEN-LAST:event_botonMostrarActionPerformed

    private void tablaActoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaActoresMousePressed
        int fila = tablaActores.getSelectedRow();
        if (fila >= 0) {
            campoClave.setText(tablaActores.getValueAt(fila, 0).toString());
            campoNombre.setText(tablaActores.getValueAt(fila, 1).toString());
            botonEliminar.setEnabled(true);
            botonActualizar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "NO A SELECCIONADO NINGUN ACTOR");
        }
    }//GEN-LAST:event_tablaActoresMousePressed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed

        actor.setCveActor(campoClave.getText());

        try {
            jpaActores.destroy(campoClave.getText());
            setModel(tablaActores);
            mostrarActores();
            campoClave.setText(null);
            campoNombre.setText(null);
            JOptionPane.showMessageDialog(null, "Actor eliminado correctamente");
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.dispose();
        MenuPrincipal menu;
        menu = new MenuPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_botonRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JTextField campoClave;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaActores;
    // End of variables declaration//GEN-END:variables
}
