/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import controles.AlbumssJpaController;
import entidades.Albums;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import objetosServicio.Fecha;

/**
 *
 * @author Francisco
 */
public class VentanaAlbums extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    public static EntityManagerFactory emf = Persistence.createEntityManagerFactory("proyectoJPAPU");
    AlbumssJpaController jpaGeneros = new AlbumssJpaController(emf);
    List listaGeneros = jpaGeneros.findAlbumssEntities();
    Albums albums = new Albums();

    /**
     * Creates new form FramePrincipal
     */
    public VentanaAlbums() {
        initComponents();
        this.setLocationRelativeTo(null);
        campoFecha.setText(new Fecha().toString());
        dtm = (DefaultTableModel) tablaAlbums.getModel();
        tablaAlbums.setModel(dtm);
        botonActualizar.setEnabled(false);
        botonEliminar.setEnabled(false);
    }

    private void mostrarAlbums() {
        setModel(tablaAlbums);
        DefaultTableModel modelo = (DefaultTableModel) tablaAlbums.getModel();
        try {
            jpaGeneros.insertarModelo(modelo);
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void setModel(JTable table) {
        while (table.getRowCount() > 0) {
            ((DefaultTableModel) table.getModel()).removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        campoFecha = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoClave = new javax.swing.JTextField();
        campoTitulo = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlbums = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoDisquera = new javax.swing.JTextField();
        botonMostrarTodos = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana Genero");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Fecha:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        campoFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(campoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 115, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Clave:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 43, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Titulo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
        getContentPane().add(campoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 111, -1));
        getContentPane().add(campoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 236, -1));

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        tablaAlbums.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre", "Tipo de Medio", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAlbums.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaAlbumsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAlbums);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 490, 190));

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(botonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Disquera:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        getContentPane().add(campoDisquera, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 180, -1));

        botonMostrarTodos.setText("Mostrar Todos");
        botonMostrarTodos.setFocusable(false);
        botonMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarTodosActionPerformed(evt);
            }
        });
        getContentPane().add(botonMostrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, 50));

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, -1, 34));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Diapositiva2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        String Clave = campoClave.getText();
        String Nombre = campoTitulo.getText();
        String Disquera = campoDisquera.getText();

        albums.setCveAlbum(Clave);
        albums.setTitulo(Nombre);
        albums.setDisquera(Disquera);
        albums.setFecha(new Date(campoFecha.getText()));

        try {
            jpaGeneros.create(albums);
            campoClave.setText(null);
            campoTitulo.setText(null);
            campoDisquera.setText(null);
            campoFecha.setText(null);
            setModel(tablaAlbums);
            mostrarAlbums();
            JOptionPane.showMessageDialog(null, "Album agregado correctamente");
        } catch (Exception e) {
            Logger.getLogger(VentanaAlbums.class.getName()).log(Level.SEVERE, null, e);
        }


    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        String Clave = campoClave.getText();
        String Nombre = campoTitulo.getText();
        String Disquera = campoDisquera.getText();

        albums.setCveAlbum(Clave);
        albums.setTitulo(Nombre);
        albums.setDisquera(Disquera);
        albums.setFecha(new Date(campoFecha.getText()));

        try {
            jpaGeneros.edit(albums);

            setModel(tablaAlbums);
            mostrarAlbums();
            JOptionPane.showMessageDialog(null, "Album actualizado correctamente");
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarTodosActionPerformed
        mostrarAlbums();
    }//GEN-LAST:event_botonMostrarTodosActionPerformed

    private void tablaAlbumsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlbumsMousePressed
        int fila = tablaAlbums.getSelectedRow();
        if (fila >= 0) {
            campoClave.setText(tablaAlbums.getValueAt(fila, 0).toString());
            campoTitulo.setText(tablaAlbums.getValueAt(fila, 1).toString());
            campoDisquera.setText(tablaAlbums.getValueAt(fila, 2).toString());
            campoFecha.setText(tablaAlbums.getValueAt(fila, 3).toString());
            botonEliminar.setEnabled(true);
            botonActualizar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "NO A SELECCIONADO NINGUN ALBUM");
        }
    }//GEN-LAST:event_tablaAlbumsMousePressed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        albums.setCveAlbum(campoClave.getText());

        try {
            jpaGeneros.destroy(campoClave.getText());
            setModel(tablaAlbums);
            mostrarAlbums();
            campoClave.setText(null);
            campoTitulo.setText(null);
            campoDisquera.setText(null);
            JOptionPane.showMessageDialog(null, "Album eliminado correctamente");
        } catch (Exception e) {
            Logger.getLogger(VentanaActor.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.dispose();
        MenuPrincipal menu;
        menu = new MenuPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_botonRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonMostrarTodos;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JTextField campoClave;
    private javax.swing.JTextField campoDisquera;
    private javax.swing.JFormattedTextField campoFecha;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAlbums;
    // End of variables declaration//GEN-END:variables
}
